spring:
  cloud:
    gateway:
      routes:
        - id: remedy-service
          uri: http://localhost:8081/remedy
          predicates:
            - Path=/remedy/**
        - id: keycloak-service
          uri: http://localhost:8090/auth
          predicates:
            - Path=/auth/**
        - id: frontend-service
          uri: http://localhost:3000
          predicates:
            - Path=/**
